version: '3.8'

services:
  jupyterhub:
    build: hub_image
    image: hub
    container_name: jupyterhub_basic
    depends_on: [notebook]
    ports:
      - "8082:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jupyterhub_step1

  notebook:
    image: phaustin/notebook:step1
    build:
      context: notebook_image
    container_name: notebook_step1

# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    jupyterhub_step1:
      driver: bridge
      name: net_basic

