version: '3.8'

services:
  jupyterhub:
    build: hub_image
    image: phaustin/jupyterhub:1.1
    container_name: jupyterhub
    depends_on: [notebook]
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jupyterhub

  notebook:
    build: notebook_image
    image: phaustin/notebook:0.1
    container_name: notebook
    
# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    jupyterhub:
      driver: bridge
      name: jupyterhub

volumes:
  jupyterhub_data:

